errorMsgs = {
    "1": "HKGolden user ID does not exist in request.",
    "2": "In-game name does not exist in request.",
    "3": "會員編號呀，唔係膠名呀，大佬。",
    "4": "乜你個會員編號真係有咁長咩[sosad]",
    "5": "唔得喎，遊戲名要最少3個字，最多20個字喎...",
    "6": "唔得呀，你個遊戲名一定要由大楷 A 至 Z, 細楷 a 至 z, 0 至 9 同埋底線( _ )組成...",
    "7": "一高登account，一遊戲account呀大佬。",
    "8": "你真係好彩，你竟然同人撞名，買六合彩啦你。",
    "11": "找不到屎船長喎，你大我呀？.jpg",
    "50": "做咩姐你，衰咁多次，抵你要等3個字先可以再繼續。",
    "100": "上唔到高登呀，一係熄登，一係bam左我IP。唔該搵搵Saren。",
    "101": "段code錯左呀，你係咪冇copy盡呀？",
    "102": "連唔到Minecraft server呀，成個注冊系統衰q左。唔該搵搵Saren。",
}